#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Minimal-risk localization: exact text replacement only. No DSP / routing / database logic changes.
REPLACEMENTS = {
    "app/src/main/res/values/strings.xml": [
        ("Snore Detector", "鼾声监测"),
    ],
    "app/src/main/java/com/aistudio/snoredetector/afkwd/MainActivity.kt": [
        ("Snore Detector", "鼾声监测"),
        ("Dashboard", "主页"),
        ("History Log", "历史记录"),
        ("History", "记录"),
        ("Configurations", "设置"),
        ("Settings", "设置"),
        ("User Guide", "使用指南"),
        ("Guide", "指南"),
        ("Mic access alert", "麦克风权限提示"),
        ("Microphone Permission Required", "需要麦克风权限"),
        ("To detect snoring sounds and compute live acoustic decibel rates, this app must access the device's microphone local streams.\\n\\nAll analytical processing is conducted 100% offline, locally, and privately. Zero tracking is stored.",
         "为了检测鼾声并实时计算声学分贝，本应用需要访问设备麦克风。\\n\\n所有分析均在本机离线完成，不上传音频，也不进行追踪。"),
        ("Grant Microphone Access", "授予麦克风权限"),
        ("FOSS Real-time Acoustic Analysis", "FOSS 实时声学分析"),
        ("SNORE!", "检测到鼾声！"),
        ("MEDIA STANDBY", "媒体播放待机"),
        ("MONITORING", "监测中"),
        ("OFF", "已停止"),
        ("Media Playback Active — Detection Standby", "正在播放媒体 — 鼾声检测已待机"),
        ("Audio playback (music / podcasts) detected. Snoring triggers are suppressed to avoid false logs. Detection resumes automatically when media stops.",
         "检测到音乐或播客播放。为避免误记录，暂时抑制鼾声触发；媒体停止后会自动恢复检测。"),
        ("STOP SESSION", "停止本次监测"),
        ("START BEDROOM SNORE MONITOR", "开始夜间鼾声监测"),
        ("Active Session Timeline Profile", "本次监测时间线"),
        ("Last Completed Session Profile", "上次监测时间线"),
        ("X-axis: Timeline progress | Y-axis: relative decibel peaks. Red regions indicate intervals satisfying current snoring criteria.",
         "横轴：时间进度｜纵轴：相对分贝峰值。红色区域表示满足当前鼾声判定条件的时段。"),
        ("Audio Input Routing", "音频输入路由"),
        ("Ready", "就绪"),
        ("Fallback Active", "正在使用备用输入"),
        ("Direct Route Active", "直接路由已启用"),
        ("Configured input:", "设定输入："),
        ("Active input:", "当前输入："),
        ("DECIBELS (dB)", "分贝 (dB)"),
        ("ACTIVE SESSION", "本次监测"),
        ("SNORES LOGGED", "鼾声记录"),
        ("1 incident", "1 次事件"),
        ("$sessionEventCount incidents", "$sessionEventCount 次事件"),
        ("Live DSP Spectrum Diagnostics:", "实时 DSP 声学诊断："),
        ("Decibels Level (RMS - Mandatory)", "分贝水平（RMS，必选）"),
        ("Zero-Crossing Rate", "过零率 ZCR"),
        ("Snore Band Energy (100-1k Hz)", "鼾声频段能量（100–1000 Hz）"),
        ("Low Frequency Ratio (<500 Hz)", "低频能量比例（<500 Hz）"),
        ("⚠️ ACTIVE SNORE PATTERN DETECTED & SAVING...", "⚠️ 检测到鼾声，正在记录…"),
        ("Threshold: $thresholdStr", "阈值：$thresholdStr"),
        ("Method Disabled", "此方法已关闭"),
        ("No metrics logged in this session.", "本次监测尚无数据。"),
        ("Audio recording saved successfully", "录音保存成功"),
        ("Failed to save audio recording", "录音保存失败"),
        ("CSV logs saved successfully", "CSV 记录保存成功"),
        ("Failed to save CSV file", "CSV 文件保存失败"),
        ("Error log exported as plain text (.txt)", "错误日志已导出为文本文件 (.txt)"),
        ("Failed to export error log", "错误日志导出失败"),
        ("Episodes (", "鼾声事件 ("),
        ("⚠️ System Errors (", "⚠️ 系统错误 ("),
        ("System Error Logs (", "系统错误日志 ("),
        ("Clear all error logs", "清空所有错误日志"),
        ("Exit selection", "退出选择"),
        (" Selected", " 已选择"),
        ("Deselect All", "取消全选"),
        ("Select All", "全选"),
        ("Export Selected", "导出已选项目"),
        ("Tracked Episodes (", "已记录事件 ("),
        ("Select episodes", "选择事件"),
        ("Export Data & Recordings", "导出数据和录音"),
        ("Clear logs", "清空记录"),
        ("Empty", "空记录"),
        ("History logs are currently empty.", "当前没有历史记录。"),
        ("Turn on the acoustics monitor on dashboard. Valid continuous snoring incidents exceeding ", "请在主页开启声学监测。持续时间超过 "),
        ("s are registered here.", " 秒且满足判定条件的鼾声事件会记录在这里。"),
        ("Audio recording unavailable for this event", "该事件没有可用录音"),
        ("Audio file is not available locally", "本地没有该录音文件"),
        ("Export $targetCount Selected Events", "导出已选的 $targetCount 个事件"),
        ("Export Recordings & Data", "导出录音和数据"),
        ("Choose an export format for personal analysis or optional review with a healthcare professional:",
         "请选择导出格式，可用于个人分析或提供给医务人员参考："),
        ("Complete Package (.zip)", "完整数据包 (.zip)"),
        ("Includes CSV logs + original WAV audio files in /audio folder", "包含 CSV 记录和 /audio 文件夹中的原始 WAV 录音"),
        ("Audio Recordings (.zip)", "录音文件 (.zip)"),
        ("Export original unaltered WAV audio files only", "仅导出未经修改的原始 WAV 录音"),
        ("CSV Session Log (.csv)", "CSV 监测记录 (.csv)"),
        ("Tabular log with timestamps, dB, RMS, ZCR, and audio references", "表格包含时间、dB、RMS、ZCR 和录音引用"),
        ("Quick Share CSV Log", "快速分享 CSV 记录"),
        ("Send CSV text directly via standard Android share sheet", "通过 Android 系统分享面板直接发送 CSV 文本"),
        ("🔒 Privacy & Health Notice", "🔒 隐私与健康提示"),
        ("• Audio files are stored locally on your device and never uploaded to any remote server.\\n• Recordings are provided for personal information and optional discussion with a healthcare professional. 鼾声监测 is not a clinical diagnostic device.",
         "• 音频仅保存在本机，不会上传到远程服务器。\\n• 录音仅供个人了解情况或与医务人员讨论。鼾声监测并非医疗诊断设备。"),
        ("Cancel", "取消"),
        ("Exporting Data", "正在导出数据"),
        ("Writing export files...", "正在写入导出文件…"),
        ("Export Completed", "导出完成"),
        ("Export Issue", "导出出现问题"),
        ("✅ Export finished successfully.", "✅ 导出成功。"),
        (" audio recording(s) exported.", " 个录音已导出。"),
        (" event(s) had no local audio clip available.", " 个事件没有本地录音。"),
        ("❌ Export encountered an error:", "❌ 导出时发生错误："),
        ("Unknown storage error.", "未知存储错误。"),
        ("Done", "完成"),
        ("Clear All History?", "清空全部历史记录？"),
        ("Are you sure you want to delete all recorded snoring events and associated local audio recordings? This action cannot be undone.",
         "确定删除全部鼾声事件及其本地录音吗？此操作无法撤销。"),
        ("Clear All", "全部清空"),
        ("Clear All System Error Logs?", "清空全部系统错误日志？"),
        ("Are you sure you want to clear all error diagnostic entries? This will not affect your tracked snoring sessions.",
         "确定清空所有错误诊断记录吗？这不会影响已记录的鼾声监测数据。"),
        ("Clear Error Logs", "清空错误日志"),
        ("Export Error Log (.txt)", "导出错误日志 (.txt)"),
        ("Share Error Log", "分享错误日志"),
        ("Delete Error Log", "删除错误日志"),
        ("View Full Diagnostics & Trace", "查看完整诊断和追踪信息"),
        ("Error Diagnostics #", "错误诊断 #"),
        ("Error Type: ", "错误类型："),
        ("Timestamp: ", "时间："),
        ("Component: ", "组件："),
        ("Message:", "信息："),
        ("Diagnostic Details & Trace:", "诊断详情与追踪："),
        ("Share Text", "分享文本"),
        ("Export .txt", "导出 .txt"),
        ("Close", "关闭"),
        ("Duration: ", "时长："),
        ("Peak: ", "峰值："),
        ("Stop Recording", "停止播放"),
        ("Play Recording", "播放录音"),
        ("Share Audio Recording", "分享录音"),
        ("Save Audio File", "保存录音文件"),
        ("Delete Event", "删除事件"),
        ("Max. RMS", "最大 RMS"),
        ("Mean ZCR", "平均 ZCR"),
        ("Band Energy", "频段能量"),
        ("Low Freq.", "低频比例"),
        ("DSP Acoustics & Detection", "DSP 声学与检测"),
        ("Signal processing filters, thresholds, duration, and formula", "信号处理滤波器、阈值、持续时间和判定公式"),
        ("Primary", "主要设置"),
        ("Detection Parameters & Acoustic Filters", "检测参数与声学滤波器"),
        ("Configure the 4 digital signal processing (DSP) acoustic filters and the duration threshold. The sound volume (amplitude dB) criterion is always active and mandatory. A snore is logged when the amplitude threshold and all other enabled filters match simultaneously (Logical AND) for the required duration.",
         "配置 4 项数字信号处理（DSP）声学条件和持续时间阈值。音量（幅度 dB）条件始终启用且不可关闭；只有音量阈值与所有已启用条件同时满足，并持续达到设定时间，才会记录为鼾声。"),
        ("1. Sound Volume (Amplitude dB)", "1. 音量（幅度 dB）"),
        ("Minimum threshold", "最小阈值"),
        ("Mandatory acoustic criterion (Value ≥ Threshold). This criterion is always active and cannot be disabled. Incoming audio must reach or exceed this decibel level to be considered for snoring detection. Normal quiet sleep acoustics are typically below 45 dB.",
         "必选声学条件（数值 ≥ 阈值），始终启用且无法关闭。输入声音必须达到或超过该分贝值才进入鼾声判定。安静睡眠环境通常低于 45 dB。"),
        ("55 dB (Always Active)", "55 dB（始终启用）"),
        ("2. Zero-Crossing Rate (Pitch)", "2. 过零率（音高）"),
        ("Maximum threshold", "最大阈值"),
        ("Maximum threshold (Value ≤ Threshold). Snoring is a low-pitched rumble with few zero-crossings. Sounds with higher frequencies (speech, whispers, hisses) exceed this limit and are filtered out.",
         "最大阈值（数值 ≤ 阈值）。鼾声通常为低频振动，过零次数较少；语音、耳语、嘶声等高频声音更容易超过该值并被过滤。"),
        ("0.150 (Enabled)", "0.150（启用）"),
        ("3. Snoring Frequency Band Energy", "3. 鼾声频段能量"),
        ("Minimum threshold (Value ≥ Threshold). Measures energy concentrated in the 100 Hz – 1,000 Hz human snoring frequency band. Filters out flat background ambient noise.",
         "最小阈值（数值 ≥ 阈值）。测量 100–1000 Hz 人体鼾声频段中的能量集中程度，用于过滤平坦的环境背景噪声。"),
        ("0.0150 (Enabled)", "0.0150（启用）"),
        ("4. Low-Frequency Energy Ratio", "4. 低频能量比例"),
        ("Minimum threshold (Value ≥ Threshold). Percentage of total sound energy located below 500 Hz. Deep airway snoring vibrations are concentrated in this low-frequency zone.",
         "最小阈值（数值 ≥ 阈值）。表示 500 Hz 以下能量占总声能的比例；气道深部鼾声振动通常集中在低频区域。"),
        ("65% (Enabled)", "65%（启用）"),
        ("5. Minimum Event Duration (Time Filter)", "5. 最短事件持续时间（时间过滤）"),
        ("Time Condition", "时间条件"),
        ("Duration threshold (Continuous persistence)", "持续时间阈值（连续满足）"),
        ("Default: 1.0s", "默认：1.0 秒"),
        ("Minimum threshold (Duration ≥ Threshold). The sound must satisfy all active acoustic filters continuously for at least this duration to be logged as a snore incident. Filters out brief noises like coughs, bed creaks, or throat clearing.",
         "最小阈值（持续时间 ≥ 阈值）。声音必须连续满足全部已启用声学条件达到该时长，才记录为鼾声事件，可过滤咳嗽、床响或清嗓等短暂噪声。"),
        ("Min: Duration ≥ ", "最短：持续时间 ≥ "),
        ("Pause Triggers During Media Playback", "媒体播放时暂停鼾声触发"),
        ("(Default: Enabled)", "（默认：开启）"),
        ("Automatically suppress false snoring triggers while podcasts, audiobooks, or music are playing on the device (e.g. while falling asleep). Snoring detection resumes automatically the moment media stops.",
         "设备播放播客、有声书或音乐时自动抑制误触发；媒体停止后立即自动恢复鼾声检测。"),
        ("General & Additional 设置", "常规与其他设置"),
        ("General & Additional Settings", "常规与其他设置"),
        ("Audio input hardware, recordings, notifications, theming, and reset", "音频输入、录音、通知、主题和重置"),
        ("Hardware & Preferences", "硬件与偏好"),
        ("Audio Input Source (Microphone)", "音频输入源（麦克风）"),
        ("Target: ", "目标："),
        ("Default Phone Microphone", "默认手机麦克风"),
        ("Scanning audio devices...", "正在扫描音频设备…"),
        ("Scan for connected audio devices", "扫描已连接的音频设备"),
        ("Choose which microphone to use for snoring detection. The app supports microphones in both wired and Bluetooth audio devices while allowing media playback—such as audiobooks, podcasts, or music—and headphone controls to continue working without interruption.",
         "选择用于鼾声检测的麦克风。支持有线和蓝牙音频设备的麦克风，同时可继续播放有声书、播客或音乐并使用耳机控制。"),
        ("Live Active Input: ", "当前实时输入："),
        (" is not currently connected. System is falling back to the default Phone Microphone automatically.", " 当前未连接，系统已自动回退到默认手机麦克风。"),
        ("Built-in", "内置"),
        ("Wired", "有线"),
        ("💡 Tip: To use a Bluetooth headset’s microphone, first connect the headset in Android 设置 → Bluetooth, then tap the Refresh button above.",
         "💡 提示：若要使用蓝牙耳机麦克风，请先在 Android 设置 → 蓝牙 中连接设备，然后点击上方刷新按钮。"),
        ("💡 Tip: To use a Bluetooth headset’s microphone, first connect the headset in Android Settings → Bluetooth, then tap the Refresh button above.",
         "💡 提示：若要使用蓝牙耳机麦克风，请先在 Android 设置 → 蓝牙 中连接设备，然后点击上方刷新按钮。"),
        ("Save Audio Recordings (.WAV)", "保存鼾声录音 (.WAV)"),
        ("Extract and persist short audio clippings of detected snoring incidents locally to play back in history logs.", "在本地保存检测到的鼾声短录音，之后可在历史记录中回放。"),
        ("Real-Time Snore Notifications", "实时鼾声通知"),
        ("(Default: Disabled)", "（默认：关闭）"),
        ("Send an immediate high-priority Android notification when a snoring incident is confirmed. Can be used with compatible notification or companion devices to provide additional alerts.",
         "确认鼾声事件后立即发送高优先级 Android 通知，也可配合兼容的通知转发或伴侣设备使用。"),
        ("Appearance & Theming", "外观与主题"),
        ("Default: System", "默认：跟随系统"),
        ("Customize the app theme mode and Material You dynamic color scheme.", "自定义应用主题模式和 Material You 动态配色。"),
        ("Theme Mode", "主题模式"),
        ("Dynamic Color (Material You)", "动态配色（Material You）"),
        ("Derive color palette from your Android wallpaper and system palette. (Default: On)", "根据 Android 壁纸和系统色板生成配色。（默认：开启）"),
        ("Reset 设置 & Parameters", "重置设置与参数"),
        ("Reset Settings & Parameters", "重置设置与参数"),
        ("Restore all 4 DSP acoustic filters, threshold parameters, minimum duration condition (1.0s), audio recording preference, microphone input source selection, and appearance settings back to their source-of-truth defaults.",
         "将 4 项 DSP 声学条件、阈值、最短持续时间（1.0 秒）、录音偏好、麦克风输入源和外观设置恢复为默认值。"),
        ("Restore All Defaults", "恢复全部默认设置"),
        ("About 鼾声监测", "关于鼾声监测"),
        ("About Snore Detector", "关于鼾声监测"),
        ("Version ", "版本 "),
        ("Open Source (FOSS) • 100% On-Device Acoustic Signal Processing", "开源（FOSS）• 100% 本机声学信号处理"),
        ("Restore Default 设置?", "恢复默认设置？"),
        ("Restore Default Settings?", "恢复默认设置？"),
        ("This will reset all detection parameters, acoustic thresholds, audio recording preferences, microphone input selection, and theming options to their original default values. Your recorded history logs will not be affected.",
         "这会将所有检测参数、声学阈值、录音偏好、麦克风输入选择和主题选项恢复为初始默认值，不会删除历史记录。"),
        ("All settings restored to defaults", "所有设置已恢复默认值"),
        ("Restore Defaults", "恢复默认值"),
        ("Active Detection Formula", "当前检测公式"),
        ("Volume (Mandatory) + $optionalFiltersCount of 3 Optional Filters", "音量（必选）+ 3 项可选条件中的 $optionalFiltersCount 项"),
        ("How snore events are determined in the detection algorithm:", "检测算法如何判定鼾声事件："),
        ("SNORE DETECTED & LOGGED =", "记录为鼾声 ="),
        ("Sound Volume (Mandatory)", "音量（必选）"),
        ("Mandatory threshold", "必选阈值"),
        ("Snore Band Energy", "鼾声频段能量"),
        ("Low-Freq Ratio (<500Hz)", "低频比例（<500 Hz）"),
        ("Continuous Duration", "连续持续时间"),
        ("Time condition", "时间条件"),
        ("Logical Rule: The mandatory sound volume threshold and every enabled optional acoustic filter must be satisfied simultaneously (Logical AND). Once met, the snoring audio must persist continuously for at least the configured duration to be recorded.",
         "逻辑规则：必选音量阈值与所有已启用的可选声学条件必须同时满足（逻辑 AND），并连续维持至少设定时长后才会记录。"),
        ("AND", "且"),
        ("Always Active", "始终启用"),
        ("Mandatory (", "必选（"),
        ("Default: ", "默认："),
        ("Min: ", "最小："),
        ("Max: ", "最大："),
    ],
    "app/src/main/java/com/aistudio/snoredetector/afkwd/ui/GuideTab.kt": [
        ("Snore Detector", "鼾声监测"),
        ("All Sections", "全部章节"),
        ("1-3 Setup & Metrics", "1–3 设置与指标"),
        ("4 Troubleshooting", "4 故障排查"),
        ("5-6 Lifestyle & Habits", "5–6 生活方式与习惯"),
        ("7-8 Medical & Scope", "7–8 医疗提示与适用范围"),
        ("9 Privacy & FOSS", "9 隐私与开源"),
        ("How to use 鼾声监测", "如何使用鼾声监测"),
        ("How to use Snore Detector", "如何使用鼾声监测"),
        ("User Guide & Information Reference", "使用指南与信息参考"),
        ("鼾声监测 listens to the sound around your bed and detects acoustic events that resemble snoring. It processes the audio locally on your phone and records detected events, their timing, duration and acoustic characteristics.",
         "鼾声监测会监听床边环境声音，识别类似鼾声的声学事件。音频在手机本地处理，并记录事件时间、持续时长和声学特征。"),
        ("Snore Detector listens to the sound around your bed and detects acoustic events that resemble snoring. It processes the audio locally on your phone and records detected events, their timing, duration and acoustic characteristics.",
         "鼾声监测会监听床边环境声音，识别类似鼾声的声学事件。音频在手机本地处理，并记录事件时间、持续时长和声学特征。"),
        ("The app is intended for personal self-monitoring, not for diagnosing medical conditions.", "本应用用于个人自我监测，不用于疾病诊断。"),
        ("Getting started", "开始使用"),
        ("For the best results:", "为了获得更好的结果："),
        ("Place your phone near the bed, with the microphone unobstructed and pointing roughly toward your head.", "将手机放在床边，确保麦克风无遮挡，并大致朝向头部。"),
        ("Keep the phone in a similar position on different nights.", "不同夜晚尽量把手机放在相近位置。"),
        ("Connect it to power if necessary.", "如有需要，请连接电源。"),
        ("Minimize background noise where practical.", "尽量减少环境背景噪声。"),
        ("Start detection before going to sleep.", "睡前开始监测。"),
        ("You do not need to place the phone directly under your pillow. Covering the microphone can interfere with recording.\\n\\nFor meaningful comparisons, use the same phone and approximately the same setup whenever possible.",
         "无需把手机直接放在枕头下面，遮挡麦克风会影响录音。\\n\\n为了便于比较，尽量使用同一部手机和相近的摆放方式。"),
        ("External Microphones & Audio Devices:", "外接麦克风与音频设备："),
        ("If you use a device with a built-in microphone, select it under Settings → Audio Input Source. 鼾声监测 captures audio from the selected device's microphone while allowing simultaneous Bluetooth or wired media playback (such as bedtime audiobooks, podcasts, or music) and use of the device's hardware buttons.",
         "如使用带麦克风的外部设备，请在 设置 → 音频输入源 中选择。鼾声监测可从所选设备麦克风采集声音，同时保留蓝牙或有线媒体播放及硬件按键功能。"),
        ("Record a night", "记录一晚"),
        ("Let 鼾声监测 run overnight without moving the phone.\\n\\nIn the morning, review:", "让鼾声监测整夜运行，期间尽量不要移动手机。\\n\\n早晨可以查看："),
        ("Let Snore Detector run overnight without moving the phone.\\n\\nIn the morning, review:", "让鼾声监测整夜运行，期间尽量不要移动手机。\\n\\n早晨可以查看："),
        ("Detected snoring events", "检测到的鼾声事件"),
        ("Time and duration of events", "事件发生时间和持续时长"),
        ("Peak acoustic level (dB)", "声学峰值（dB）"),
        ("Low-frequency ratio & frequency energy", "低频比例和频段能量"),
        ("Optional audio clips", "可选录音片段"),
        ("A single night can be misleading. For personal tracking, it is more useful to compare several nights and look for recurring patterns.\\n\\nYou may also note factors such as sleep position, alcohol consumption, congestion, meal timing or unusual fatigue. This can help you identify personal patterns.",
         "单晚结果可能具有偶然性。个人追踪更适合比较多个夜晚，寻找重复出现的规律。\\n\\n也可以记录睡姿、饮酒、鼻塞、进食时间或异常疲劳等因素，以帮助发现个人模式。"),
        ("Real-Time Snoring Alerts:", "实时鼾声提醒："),
        ("If enabled in Settings, the app generates a high-priority Android notification immediately when a snoring incident is confirmed. This provides an instant alert on your device and can optionally be used with compatible notification or companion devices to provide additional alerts.",
         "在设置中开启后，一旦确认鼾声事件，应用会立即发送高优先级 Android 通知，也可配合兼容的通知转发或伴侣设备使用。"),
        ("Understanding the results", "理解监测结果"),
        ("鼾声监测 identifies sounds that match characteristics of snoring. Its measurements are acoustic measurements, not clinical measurements of sleep or breathing.", "鼾声监测识别具有鼾声特征的声音。这里的指标属于声学测量，不是临床睡眠或呼吸生理指标。"),
        ("Sound Volume (Decibels dB) — Mandatory Criterion", "音量（分贝 dB）— 必选条件"),
        ("Shows how strong the recorded audio signal was in decibels (dB) calculated from RMS power. This amplitude criterion is always active and mandatory for detection. Adjust the detection threshold to match your room’s acoustics and the level of background noise picked up by the microphone.",
         "显示根据 RMS 功率计算的录音信号强度（dB）。该幅度条件始终启用，是检测的必选条件。可根据房间声学环境和麦克风拾取的背景噪声调整阈值。"),
        ("Zero-Crossing Rate (ZCR / Pitch)", "过零率（ZCR / 音高）"),
        ("Describes how often the audio waveform crosses zero. Snoring is a low-pitched rumble with few zero-crossings, distinguishing it from higher-pitched sounds.", "表示音频波形穿过零点的频率。鼾声通常是低频振动，过零次数较少，可用于和较高频声音区分。"),
        ("Snoring Frequency Band Energy", "鼾声频段能量"),
        ("Measures acoustic energy concentrated in the 100 Hz – 1,000 Hz human snoring frequency band, filtering out flat background noise.", "测量 100–1000 Hz 人体鼾声频段中的声能集中程度，用于过滤平坦的背景噪声。"),
        ("Low-Frequency Energy Ratio", "低频能量比例"),
        ("Compares energy below 500 Hz with total spectral energy. Deep airway snoring vibrations are concentrated in this low-frequency zone.", "比较 500 Hz 以下能量与总频谱能量。气道深部鼾声振动通常集中于这一低频区域。"),
        ("Event Duration", "事件持续时间"),
        ("The duration in seconds during which the sound continuously satisfied all active acoustic criteria.", "声音连续满足全部已启用声学条件的时间，单位为秒。"),
        ("No snoring detected?", "没有检测到鼾声？"),
        ("\"No detection\" does not necessarily mean that you did not snore.\\n\\nPossible reasons include:", "“未检测到”并不一定表示你没有打鼾。\\n\\n可能原因包括："),
        ("You did not snore that night", "当晚确实没有打鼾"),
        ("The phone was too far away", "手机离得太远"),
        ("The microphone was obstructed", "麦克风被遮挡"),
        ("The selected audio input device was disconnected or unselected", "选择的音频输入设备已断开或未正确选择"),
        ("Background noise affected detection", "背景噪声影响检测"),
        ("The detection threshold was too high", "检测阈值设置过高"),
        ("The selected algorithms were not suitable for the recording", "所选算法参数不适合该录音环境"),
        ("Your phone's microphone or audio processing differs from other devices", "你的手机麦克风或音频处理方式与其他设备不同"),
        ("Before changing parameters, check the phone placement and microphone.\\n\\nIf detection appears too insensitive, try:", "调整参数前，先检查手机摆放和麦克风。\\n\\n如果检测过于不敏感，可以尝试："),
        ("Move the phone somewhat closer.", "把手机适当放近一些。"),
        ("Make sure the microphone is unobstructed.", "确保麦克风没有被遮挡。"),
        ("Adjust the relevant sensitivity/threshold gradually.", "逐步调整相关灵敏度或阈值。"),
        ("Change one parameter at a time.", "每次只改一个参数。"),
        ("Compare several nights.", "比较多个夜晚的结果。"),
        ("⚠️ Lowering a threshold can increase sensitivity, but it can also increase false detections.", "⚠️ 降低阈值可以提高灵敏度，但也可能增加误报。"),
        ("What can help with snoring?", "哪些方法可能有助于减少打鼾？"),
        ("Evidence-Based Lifestyle Factors", "有一定证据支持的生活方式因素"),
        ("Some factors are associated with snoring and sleep-disordered breathing. Depending on the individual situation, you may consider:", "一些因素与打鼾和睡眠呼吸障碍有关，可根据个人情况考虑："),
        ("Sleeping position", "睡姿"),
        ("If you notice more snoring while sleeping on your back, try sleeping on your side or using an appropriate positional strategy. Positional therapy and head-of-bed elevation have some evidence for reducing snoring in certain people, although the effect varies between individuals.",
         "如果仰睡时鼾声明显增多，可尝试侧睡或合适的体位干预。对部分人而言，体位治疗或适度抬高床头可能减少打鼾，但个体差异较大。"),
        ("Alcohol", "酒精"),
        ("Alcohol close to bedtime can worsen snoring and sleep-disordered breathing in some people. Avoiding alcohol near bedtime may therefore be worth trying.", "睡前饮酒可能加重部分人的打鼾和睡眠呼吸障碍，因此可尝试避免临睡前饮酒。"),
        ("Healthy weight", "健康体重"),
        ("If you are overweight, healthy and sustainable weight management may improve sleep-disordered breathing. This does not mean that everyone who snores needs to lose weight.", "如果超重，健康且可持续的体重管理可能改善睡眠呼吸障碍，但并不意味着所有打鼾者都需要减重。"),
        ("Physical activity", "规律运动"),
        ("Regular physical activity is beneficial for general health and is also part of lifestyle approaches used in managing sleep-disordered breathing.", "规律运动有益于整体健康，也是管理睡眠呼吸障碍时常采用的生活方式措施之一。"),
        ("Nasal congestion", "鼻塞"),
        ("A blocked nose can contribute to snoring in some people. If nasal congestion is persistent, consider discussing the cause and appropriate treatment with a healthcare professional.", "鼻塞可能加重部分人的打鼾。如果长期鼻塞，建议与医务人员讨论原因和合适的处理方式。"),
        ("Commonly suggested lifestyle ideas — evidence is limited or unclear", "常见生活方式建议 — 证据有限或不明确"),
        ("🟡 Evidence: Limited / Unclear", "🟡 证据：有限 / 不明确"),
        ("When should I talk to a doctor?", "什么时候应该就医？"),
        ("Important Medical Guidance", "重要医疗提示"),
        ("Loudness alone does not determine whether snoring is medically significant.\\n\\nSome people with relatively quiet snoring have sleep apnea, while others who snore loudly do not.",
         "仅凭鼾声音量无法判断医学风险。\\n\\n有些鼾声并不响的人存在睡眠呼吸暂停，而有些鼾声很响的人并没有。"),
        ("Consider discussing your symptoms with a healthcare professional if snoring is accompanied by:", "如果打鼾同时伴有以下情况，建议向医务人员咨询："),
        ("Witnessed pauses in breathing", "他人观察到睡眠中呼吸暂停"),
        ("Choking or gasping during sleep", "睡眠中憋醒、呛咳或喘气"),
        ("Excessive daytime sleepiness", "白天过度嗜睡"),
        ("Morning headaches", "晨起头痛"),
        ("High blood pressure", "高血压"),
        ("Persistent or severe snoring", "持续或严重打鼾"),
        ("Unexplained fatigue or concentration problems", "原因不明的疲劳或注意力问题"),
        ("A healthcare professional may recommend an appropriate sleep evaluation.\\n\\nImportantly, an improvement in your 鼾声监测 recordings does not rule out sleep apnea, and continued snoring does not prove that you have it.\\n\\nIf obstructive sleep apnea is diagnosed, treatment should be discussed with a healthcare professional. Depending on the individual situation, treatment may include positive airway pressure (PAP/CPAP), among other options.",
         "医务人员可能会建议进行合适的睡眠评估。\\n\\n需要注意：鼾声监测结果改善不能排除睡眠呼吸暂停；持续打鼾也不能证明一定患有睡眠呼吸暂停。\\n\\n如果确诊阻塞性睡眠呼吸暂停，应与医务人员讨论治疗方案，可能包括 PAP/CPAP 等。"),
        ("What 鼾声监测 can and cannot tell you", "鼾声监测能告诉你什么、不能告诉你什么"),
        ("What Snore Detector can and cannot tell you", "鼾声监测能告诉你什么、不能告诉你什么"),
        ("The app analyzes sound, not your complete sleep physiology.", "本应用分析的是声音，而不是完整的睡眠生理信号。"),
        ("鼾声监测 can help you:", "鼾声监测可以帮助你："),
        ("Detect sounds resembling snoring", "识别类似鼾声的声音"),
        ("Observe patterns across multiple nights", "观察多个夜晚的规律"),
        ("Identify possible environmental influences", "发现可能的环境影响因素"),
        ("Compare recordings before and after personal changes", "比较个人调整前后的录音"),
        ("Listen to selected audio clips", "回听所选录音片段"),
        ("Keep a local history", "保留本地历史记录"),
        ("Export your data for personal analysis or discussion with a healthcare professional", "导出数据用于个人分析或与医务人员讨论"),
        ("鼾声监测 cannot determine:", "鼾声监测无法判断："),
        ("Whether you have sleep apnea", "你是否患有睡眠呼吸暂停"),
        ("Your apnea-hypopnea index (AHI)", "你的呼吸暂停低通气指数（AHI）"),
        ("Your blood oxygen level", "你的血氧水平"),
        ("Whether breathing actually stopped", "呼吸是否真正停止"),
        ("Your sleep stages", "你的睡眠分期"),
        ("Respiratory effort", "呼吸努力程度"),
        ("The medical severity of snoring", "打鼾的医学严重程度"),
        ("Which treatment is appropriate for you", "哪种治疗适合你"),
        ("Privacy & FOSS", "隐私与开源"),
        ("100% On-Device & FOSS", "100% 本机处理与开源"),
        ("鼾声监测 is designed around local, user-controlled data.\\n\\nAudio processing and event detection take place on your device. Your recordings and detection history do not need to be uploaded to a server.\\n\\nYou can review your history locally and export your detection data when you choose.\\n\\nThe application is free and open source, allowing users to inspect and contribute to the software.\\n\\nLike other consumer self-monitoring tools, 鼾声监测 provides information rather than a medical diagnosis.",
         "鼾声监测以本地、由用户控制的数据为核心设计。\\n\\n音频处理和事件检测均在设备上完成，录音和历史记录无需上传服务器。\\n\\n你可以在本地查看历史，并在需要时导出数据。\\n\\n本应用免费且开源，用户可以查看源码并参与改进。\\n\\n与其他消费级自我监测工具一样，它提供的是信息，而不是医疗诊断。"),
        ("Medical Disclaimer", "医疗免责声明"),
        ("Important Medical Disclaimer", "重要医疗免责声明"),
        ("鼾声监测 is a self-monitoring and information tool. It is not a medical diagnostic device and cannot diagnose or rule out sleep apnea or other medical conditions.\\n\\nIf you are concerned about your breathing during sleep or have symptoms such as pauses in breathing, gasping/choking, excessive daytime sleepiness, morning headaches or high blood pressure, please discuss them with a qualified healthcare professional.",
         "鼾声监测是一款自我监测与信息工具，并非医疗诊断设备，不能诊断或排除睡眠呼吸暂停及其他疾病。\\n\\n如果你担心睡眠中的呼吸情况，或存在呼吸暂停、憋气/呛醒、白天过度嗜睡、晨起头痛或高血压等症状，请咨询合格的医务人员。"),
        ("Collapse", "收起"),
        ("Expand", "展开"),
    ],
    "app/src/main/java/com/aistudio/snoredetector/afkwd/service/SnoreDetectionService.kt": [
        ("Media playback active — Detection on standby", "正在播放媒体 — 鼾声检测待机"),
        ("Monitoring bedroom acoustics dynamically...", "正在监测卧室声学环境…"),
        ("Ready to analyze...", "准备开始分析…"),
        ("Snoring audio detected in progress...", "正在检测鼾声…"),
        ("Snoring Detected", "检测到鼾声"),
        ("A snoring incident was detected.", "检测到一次鼾声事件。"),
        ("Snore Detector Active", "鼾声监测运行中"),
        ("Stop Monitoring", "停止监测"),
        ("Acoustics Monitoring Service", "声学监测服务"),
        ("Real-time snoring sound detection, FFT analysis, and offline persistence", "实时鼾声检测、FFT 分析和本地离线保存"),
        ("Snoring Event Alerts", "鼾声事件提醒"),
        ("Real-time notifications sent immediately when a snoring episode is confirmed", "确认鼾声事件后立即发送实时通知"),
        ("Hardware microphonic recording not supported", "当前硬件不支持麦克风录音"),
        ("Microphone record audio permissions not granted", "未授予麦克风录音权限"),
        ("Failed to initialize microphone hardware. Device might be busy.", "麦克风硬件初始化失败，设备可能正被占用。"),
    ],
    "app/src/main/java/com/aistudio/snoredetector/afkwd/viewmodel/SnoreViewModel.kt": [
        ("Snore Detector Error Log - ", "鼾声监测错误日志 - "),
        ("Share Error Log", "分享错误日志"),
        ("Exporting audio recording...", "正在导出录音…"),
        ("Exporting CSV log...", "正在导出 CSV 记录…"),
        ("Preparing export package (0/", "正在准备导出包（0/"),
        ("Exporting recording $current of $total...", "正在导出录音 $current / $total…"),
        ("Failed to create ZIP package", "创建 ZIP 数据包失败"),
        ("Snore Detector Session Log", "鼾声监测记录"),
        ("Share Snoring Log CSV", "分享鼾声 CSV 记录"),
    ],
}


def apply(path_str, pairs):
    path = ROOT / path_str
    if not path.exists():
        print(f"[skip] {path_str} not found")
        return 0
    text = path.read_text(encoding="utf-8")
    original = text
    hits = 0
    for old, new in pairs:
        n = text.count(old)
        if n:
            text = text.replace(old, new)
            hits += n
    if text != original:
        path.write_text(text, encoding="utf-8")
        print(f"[ok] {path_str}: {hits} replacements")
    else:
        print(f"[nochange] {path_str}")
    return hits


def main():
    total = 0
    for path, pairs in REPLACEMENTS.items():
        total += apply(path, pairs)
    print(f"Localization complete: {total} exact replacements")


if __name__ == "__main__":
    main()
